version: "3"
services:
  short_url:
    container_name: url-service
    image: short_url:v1.0
    restart: always
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python main.py